# Masking options for mask_face_region
FACE_OVAL_MASK = 1
FACE_SKIN_MASK = 2
EYES_MASK = 3
IRISES_MASK = 21
LIPS_MASK = 22
HEMI_FACE_LEFT_MASK = 23
HEMI_FACE_RIGHT_MASK = 24
HEMI_FACE_BOTTOM_MASK = 25
HEMI_FACE_TOP_MASK = 26
EYES_NOSE_MOUTH_MASK = 14
MASK_OPTIONS = [FACE_OVAL_MASK, FACE_SKIN_MASK, EYES_MASK, IRISES_MASK, LIPS_MASK, HEMI_FACE_LEFT_MASK,
                HEMI_FACE_RIGHT_MASK, HEMI_FACE_BOTTOM_MASK, HEMI_FACE_TOP_MASK, EYES_NOSE_MOUTH_MASK]

# Compatible color spaces for extract_color_channel_means and face_color_shift
COLOUR_SPACE_BGR = 47
COLOR_SPACE_BGR = COLOUR_SPACE_BGR
COLOUR_SPACE_HSV = 48
COLOR_SPACE_HSV = COLOUR_SPACE_HSV
COLOUR_SPACE_GREYSCALE = 49
COLOR_SPACE_GRAYSCALE = COLOUR_SPACE_GREYSCALE
COLOR_SPACE_OPTIONS = [COLOUR_SPACE_BGR, COLOR_SPACE_BGR, COLOUR_SPACE_HSV, COLOR_SPACE_HSV, COLOUR_SPACE_GREYSCALE, COLOR_SPACE_GRAYSCALE]
COLOUR_SPACE_OPTIONS = COLOR_SPACE_OPTIONS

# Shift Color options
COLOR_RED = 4
COLOUR_RED = COLOR_RED
COLOR_BLUE = 5
COLOUR_BLUE = COLOR_BLUE
COLOR_GREEN = 6
COLOUR_GREEN = COLOR_GREEN
COLOR_YELLOW = 7
COLOUR_YELLOW = COLOR_YELLOW
SHIFT_COLOR_OPTIONS = [COLOUR_RED, COLOR_RED, COLOUR_BLUE, COLOR_BLUE, COLOUR_GREEN, COLOR_GREEN, COLOUR_YELLOW, COLOR_YELLOW]
SHIFT_COLOUR_OPTIONS = SHIFT_COLOR_OPTIONS

# Fill options for occluded face regions
OCCLUSION_FILL_BLACK = 8
OCCLUSION_FILL_MEAN = 9

# Blurring methods
BLUR_METHOD_AVERAGE = 11
BLUR_METHOD_GAUSSIAN = 12
BLUR_METHOD_MEDIAN = 13

# Noise methods
NOISE_METHOD_PIXELATE = 18
NOISE_METHOD_SALT_AND_PEPPER = 19
NOISE_METHOD_GAUSSIAN = 20

# Grid shuffling methods
LOW_LEVEL_GRID_SHUFFLE = 27
HIGH_LEVEL_GRID_SHUFFLE = 28

# Point Light Display History Modes
SHOW_HISTORY_ORIGIN = 32
SHOW_HISTORY_RELATIVE = 33

# Frame Shuffle methods
FRAME_SHUFFLE_RANDOM = 34
FRAME_SHUFFLE_RANDOM_W_REPLACEMENT = 35
FRAME_SHUFFLE_REVERSE = 36
FRAME_SHUFFLE_RIGHT_CYCLIC_SHIFT = 37
FRAME_SHUFFLE_LEFT_CYCLIC_SHIFT = 38
FRAME_SHUFFLE_PALINDROME = 39
FRAME_SHUFFLE_INTERLEAVE = 40

FRAME_SHUFFLE_METHODS = [FRAME_SHUFFLE_RANDOM, FRAME_SHUFFLE_RANDOM_W_REPLACEMENT, FRAME_SHUFFLE_REVERSE, 
                   FRAME_SHUFFLE_RIGHT_CYCLIC_SHIFT, FRAME_SHUFFLE_LEFT_CYCLIC_SHIFT, FRAME_SHUFFLE_PALINDROME,
                   FRAME_SHUFFLE_INTERLEAVE]

# image to video methods
STANDARDISE_DIMS_CROP = 41
STANDARDIZE_DIMS_CROP = STANDARDISE_DIMS_CROP
STANDARDISE_DIMS_PAD = 42
STANDARDIZE_DIMS_PAD = STANDARDISE_DIMS_PAD

# Image Overlay Specifiers
OVERLAY_SUNGLASSES = 43
OVERLAY_GLASSES = 44
OVERLAY_TEAR = 45
OVERLAY_SWEAT = 46